# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 600)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #D2DBE0;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainGridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.mainGridLayout.setObjectName("mainGridLayout")
        self.emojiScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.emojiScrollArea.setStyleSheet("border: 0px;")
        self.emojiScrollArea.setWidgetResizable(True)
        self.emojiScrollArea.setObjectName("emojiScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 791, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.emojiGridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.emojiGridLayout.setObjectName("emojiGridLayout")
        self.emojiScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainGridLayout.addWidget(self.emojiScrollArea, 2, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.mainGridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.filterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.filterBtn.setStyleSheet("")
        self.filterBtn.setObjectName("filterBtn")
        self.mainGridLayout.addWidget(self.filterBtn, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.mainGridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.mainGridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 21))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setStyleSheet("")
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "顏文字庫"))
        self.label.setText(_translate("MainWindow", "顏文字"))
        self.filterBtn.setText(_translate("MainWindow", "過濾"))
        self.menu.setTitle(_translate("MainWindow", "說明"))
        self.action.setText(_translate("MainWindow", "線上說明"))
        self.action_2.setText(_translate("MainWindow", "關於"))
